kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: webapp2-allow
spec:
  podSelector:
    matchLabels:
      app: web2
  ingress:
  - from:
      - podSelector:
          matchLabels:
            access: accepted
