apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: webapp2
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2
spec:
  type: ClusterIP
  selector:
    app: app2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
