---
kind: Namespace
apiVersion: v1
metadata:
  name: cau2
  labels:
    name: cau2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
  namespace: cau2
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/minhtuan1407/vol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume
  namespace: cau2
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: cau2
spec:
  containers:
  - name: c1
    image: busybox:1.31.1
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(hostname) $(date) >> /vol/date.log; sleep 5; done"]
    volumeMounts:
    - name: my-volume
      mountPath: /vol
  volumes:
  - name: my-volume 
    emptyDir: {}
    
