---
kind: Namespace
apiVersion: v1
metadata:
  name: cau2
  labels:
    name: cau2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume
  namespace: cau2
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: cau2
spec:
  containers:
  - name: c1
    image: busybox:1.31.1
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo $(hostname) $(date) >> /vol/date.log; sleep 5; done"]
    volumeMounts:
    - name: my-volume
      mountPath: /var/log
  - name: c2
    image: busybox:1.31.1
    volumeMounts:
    - name: my-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: my-volume 
    emptyDir: {}
    
